apiVersion: v1
kind: DeploymentConfig
metadata:
  name: blackbox-exporter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blackbox-exporter
        version: "latest"
    spec:
      nodeSelector: {"region":"infra"}
      containers:
      - name: blackbox-exporter
        image: REGISTRY-IP:5000/openshift/blackbox-exporter:latest
        ports:
        - containerPort: 9115
